"""Adjust migration for correct models

Revision ID: 319fc88acaec
Revises: effedd8d1e85
Create Date: 2024-02-08 17:12:02.148872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319fc88acaec'
down_revision = 'effedd8d1e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
